name: example
description: Flutter example for check app version

publish_to: 'none'

version: 1.5.0+35

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  check_app_version:
    path: ../

  package_info_plus: ^1.4.3+1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
